- id: gradle-ktfmt
  name: gradle-ktfmt
  description: Runs ktfmt on Kotlin source and script files.
  language: unsupported_script
  entry: gradlew ktfmtPreCommit
  files: '\\.(kt|kts)$'
  pass_filenames: false
