- id: gradle-ktfmt
  name: gradle-ktfmt
  description: Runs ktfmt on Kotlin source and script files.
  language: unsupported_script
  entry: gradlew --no-daemon ktfmtPreCommit
  pass_filenames: false
