name: Easeatten Android Tagged Release

on:
  push:
    tags: [ "v*" ]

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            app/src/main/rust/sxcapi/target/
          key: tagged-release-${{ runner.os }}-cargo-${{ hashFiles('app/src/main/rust/sxcapi/Cargo.lock') }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: jetbrains

      # Configure Gradle for optimal use in GitHub Actions, including caching
      # of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Rust toolchain
        run: rustup target add armv7-linux-androideabi aarch64-linux-android x86_64-linux-android

      - name: Install Rust crate `cargo-ndk`
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-ndk

      - name: Install Rust crate `uniffi-bindgen`
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: uniffi
          features: cli

      - name: Assemble with Gradle
        run: ./gradlew assemble

      - name: Sign APKs
        uses: upup-company/apksigner-android@v1
        id: apksigner
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.APKSIGNER_SIGNING_KEY }}
          alias: ${{ secrets.APKSIGNER_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APKSIGNER_KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: | # APK files for ABIs: armeabi-v7a, arm64-v8a, x86_64
            ${{ steps.apksigner.outputs.signedReleaseFile0 }}
            ${{ steps.apksigner.outputs.signedReleaseFile1 }}
            ${{ steps.apksigner.outputs.signedReleaseFile2 }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
